Require base >= 4.11.
Fails to build with base <= 10 / ghc 8.2 due to the missing Semigroup
class:

Data/Ranged/RangedSet.hs:74:31: error:
    Not in scope: type constructor or class ‘Semigroup’
   |
74 | instance DiscreteOrdered a => Semigroup (RSet a) where
   |                               ^^^^^^^^^